// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCQuFEk7KoKiYGHbl7mqPJA3xCz5L2u7c',
    appId: '1:287871342191:web:d3ea4782d3ae60aad41f9a',
    messagingSenderId: '287871342191',
    projectId: 'agroclimate-cde98',
    authDomain: 'agroclimate-cde98.firebaseapp.com',
    storageBucket: 'agroclimate-cde98.appspot.com',
    measurementId: 'G-6VMXD2QS2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzoQI5TD_XU40PSO8PRLI8rVkQA0PyVKM',
    appId: '1:287871342191:android:a1f5327fbf50e61fd41f9a',
    messagingSenderId: '287871342191',
    projectId: 'agroclimate-cde98',
    storageBucket: 'agroclimate-cde98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ55CDEFrGrDdw9FY_F3n_FJ-PWYF4gdI',
    appId: '1:287871342191:ios:9f81b172aec6d3aad41f9a',
    messagingSenderId: '287871342191',
    projectId: 'agroclimate-cde98',
    storageBucket: 'agroclimate-cde98.appspot.com',
    iosClientId: '287871342191-ad7evnr1ie4lf3qiqcudppmbqd6pb660.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmers',
  );
}
